DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    username VARCHAR(32) NOT NULL,
    password VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    sex TINYINT NOT NULL DEFAULT 1,
    id_number VARCHAR(18) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user BIGINT NOT NULL DEFAULT 0,
    update_user BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_employee_username UNIQUE (username),
    CONSTRAINT uk_employee_id_number UNIQUE (id_number)
);

CREATE INDEX idx_employee_name ON employee (name);
CREATE INDEX idx_employee_status ON employee (status);

INSERT INTO employee (
    id,
    name,
    username,
    password,
    phone,
    sex,
    id_number,
    status,
    create_time,
    update_time,
    create_user,
    update_user
) VALUES
    (
        1,
        'Admin',
        'admin',
        '$2a$10$ruVkHLSTd394.6B77k7UrOJSPZsqJHQ5llLFgM48qpiHkMdDvSU7u',
        '13800000001',
        1,
        '110101199001010011',
        1,
        '2026-09-19 10:00:00',
        '2026-09-19 10:00:00',
        1,
        1
    ),
    (
        2,
        'Operator',
        'operator',
        '$2a$10$ruVkHLSTd394.6B77k7UrOJSPZsqJHQ5llLFgM48qpiHkMdDvSU7u',
        '13800000002',
        2,
        '110101199002020022',
        0,
        '2026-09-19 11:00:00',
        '2026-09-19 11:00:00',
        1,
        1
    );

DROP TABLE IF EXISTS category;

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TINYINT NOT NULL,
    name VARCHAR(32) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user BIGINT NOT NULL DEFAULT 0,
    update_user BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_category_type_name UNIQUE (type, name)
);

CREATE INDEX idx_category_type_sort ON category (type, sort);
CREATE INDEX idx_category_status ON category (status);

INSERT INTO category (
    id,
    type,
    name,
    sort,
    status,
    create_time,
    update_time,
    create_user,
    update_user
) VALUES
    (
        1,
        1,
        'Hot Dishes',
        10,
        1,
        '2026-09-19 10:00:00',
        '2026-09-19 10:00:00',
        1,
        1
    ),
    (
        2,
        2,
        'Set Meals',
        10,
        1,
        '2026-09-19 11:00:00',
        '2026-09-19 11:00:00',
        1,
        1
    );

DROP TABLE IF EXISTS dish_flavor;
DROP TABLE IF EXISTS dish;

CREATE TABLE dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    category_id BIGINT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255),
    description VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user BIGINT NOT NULL DEFAULT 0,
    update_user BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_dish_category_id ON dish (category_id);
CREATE INDEX idx_dish_name ON dish (name);
CREATE INDEX idx_dish_status ON dish (status);

CREATE TABLE dish_flavor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id BIGINT NOT NULL,
    name VARCHAR(32) NOT NULL,
    value_json VARCHAR(1000) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user BIGINT NOT NULL DEFAULT 0,
    update_user BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_dish_flavor_dish_id ON dish_flavor (dish_id);

DROP TABLE IF EXISTS setmeal_dish;
DROP TABLE IF EXISTS setmeal;

CREATE TABLE setmeal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(32) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    description VARCHAR(255),
    image VARCHAR(255),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user BIGINT NOT NULL DEFAULT 0,
    update_user BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_setmeal_category_name UNIQUE (category_id, name)
);

CREATE INDEX idx_setmeal_category_id ON setmeal (category_id);
CREATE INDEX idx_setmeal_status ON setmeal (status);

CREATE TABLE setmeal_dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setmeal_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    copies INT NOT NULL DEFAULT 1,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user BIGINT NOT NULL DEFAULT 0,
    update_user BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_setmeal_dish UNIQUE (setmeal_id, dish_id)
);

CREATE INDEX idx_setmeal_dish_dish_id ON setmeal_dish (dish_id);

DROP TABLE IF EXISTS user_account;

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid VARCHAR(64) NOT NULL,
    name VARCHAR(32),
    phone VARCHAR(20),
    sex TINYINT,
    avatar VARCHAR(255),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_account_openid UNIQUE (openid)
);

DROP TABLE IF EXISTS shopping_cart;

CREATE TABLE shopping_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    dish_id BIGINT,
    setmeal_id BIGINT,
    quantity INT NOT NULL DEFAULT 1,
    flavor VARCHAR(255),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_shopping_cart_user_dish UNIQUE (user_id, dish_id),
    CONSTRAINT uk_shopping_cart_user_setmeal UNIQUE (user_id, setmeal_id)
);

CREATE INDEX idx_shopping_cart_user_id ON shopping_cart (user_id);

DROP TABLE IF EXISTS address_book;

CREATE TABLE address_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    consignee VARCHAR(32) NOT NULL,
    sex TINYINT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    province_name VARCHAR(32) NOT NULL,
    city_name VARCHAR(32) NOT NULL,
    district_name VARCHAR(32) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    label VARCHAR(32),
    is_default TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_address_book_user_id ON address_book (user_id);
CREATE INDEX idx_address_book_user_default ON address_book (user_id, is_default);

DROP TABLE IF EXISTS order_detail;
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(32) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL,
    address_book_id BIGINT NOT NULL,
    order_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checkout_time TIMESTAMP,
    pay_method TINYINT NOT NULL,
    pay_status TINYINT NOT NULL DEFAULT 0,
    amount DECIMAL(10, 2) NOT NULL,
    remark VARCHAR(255),
    phone VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    consignee VARCHAR(32) NOT NULL,
    cancel_reason VARCHAR(255),
    cancel_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_orders_number UNIQUE (number)
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_order_time ON orders (order_time);

CREATE TABLE order_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    name VARCHAR(32) NOT NULL,
    image VARCHAR(255),
    dish_id BIGINT,
    setmeal_id BIGINT,
    dish_flavor VARCHAR(255),
    number INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_detail_order_id ON order_detail (order_id);
